# Generated by Django 5.2.3 on 2025-11-21 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatehistory',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='คะแนน 1-5 ดาว', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
