# Generated by Django 5.2.3 on 2026-01-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatehistory',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='generated_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='generatehistory',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
